name: polite_betrayal
description: "Polite Betrayal - A Diplomacy Game"
publish_to: 'none'
version: 0.6.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  web_socket_channel: ^3.0.2
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  http: ^1.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/map/
